### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by Rohit-Satyam** [yuexujiang/MULocDeep#2]
Dear developers

I was trying to screen 3800 protein sequences that I have to predict their sub-cellular localization. We have ToxoLOPIT dataset published [here](https://proteome.shinyapps.io/toxolopittzex/) and we were wondering if we could check how well your tool performs on in sub-cellular localisation of the proteins we have localization information about. We were able to install your tool as follows:

```
mamba create -n mulocdeep -c conda-forge -c bioconda python keras=2.3 tensorflow-gpu=1.13.1 blast biopython matplotlib
```

However, when we run the tool on your dataset using `python predict.py -input wiki_seq.txt -output ./test --att --cpu` we get the following error:

```
Instructions for updating:
Colocations handled automatically by placer.
2024-02-13 00:04:42.373273: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2024-02-13 00:04:42.401484: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000000000 Hz
2024-02-13 00:04:42.405213: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55f213e0da50 executing computations on platform Host. Devices:
2024-02-13 00:04:42.405247: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "predict.py", line 285, in <module>
    main()
  File "predict.py", line 146, in main
    model_small.load_weights('./gpu_model_40nr/fold' + str(foldnum) + '_big_lv1_acc-weights.hdf5')
  File "miniconda3/envs/mulocdeep/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "miniconda3/envs/mulocdeep/lib/python3.7/site-packages/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "miniconda3/envs/mulocdeep/lib/python3.7/site-packages/keras/engine/saving.py", line 1183, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

```

Besides, I don't understand why the tool says `invalid protein` in the logs?

```
ID: P11893
Name: P11893
Description: P11893
Number of features: 0
Seq('invalid protein: MVAMAMASLQSSMSSLSLSSNSFLGQPLSPITLSPFL...AAT')
```

I want to use the command line version because we want to check its efficiency on the Toxo dataset and see if we can harness some insights and that too with accuracy for other apicomplexans (especially proteins we are working on) and also because here our testing dataset has a huge number (~3800 as compared to 200 protein sequences limit your server provides)).  For some proteins from the ToxoLOPIT database, I saw that your server gave an accurate estimation (when compared to the experimentally assigned localization) compared to `DeepLoc - 2.0` so I am a bit motivated to use this.

**Comment by yuexujiang** [comment]
Hi Rohit,

For the invalid protein issue, that is caused by the blast. Please make
sure the blast program is properly installed and the "db" folder is placed
under the working directory.
As to the attributeError, I am not quite sure what cause it. I tested it
several times and it runs just fine, even there is invalid protein issue.
So could you send me some details of your system?

Thanks,
-Yuexu

**Comment by Rohit-Satyam** [comment]
Hi here are my system specs

```
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 57 bits virtual
CPU(s):                             112
On-line CPU(s) list:                0-111
Thread(s) per core:                 2
Core(s) per socket:                 28
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              106
Model name:                         Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz
Stepping:                           6
Frequency boost:                    enabled
CPU MHz:                            800.100
CPU max MHz:                        2001.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4000.00
Virtualization:                     VT-x
L1d cache:                          2.6 MiB
L1i cache:                          1.8 MiB
L2 cache:                           70 MiB
L3 cache:                           84 MiB
NUMA node0 CPU(s):                  0-27,56-83
NUMA node1 CPU(s):                  28-55,84-111
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
```

I am launching my script from the `MULocDeep` folder itself. The blast is in the path when checked with `which blastp` as can be seen below `miniconda3/envs/mulocdeep/bin/blastp` and the version is `Protein-Protein BLAST 2.15.0+`

**Comment by Rohit-Satyam** [comment]
I also tried using the version you provide on your [website](https://www.mu-loc.org/tools) using `mamba env create -f MULocDeep_conda.yaml ` but I keep on getting the following error:

```
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested m2w64-bwidget 1.9.10**
  - nothing provides requested m2w64-bzip2 1.0.6**
  - nothing provides requested m2w64-expat 2.1.1**
  - nothing provides requested m2w64-fftw 3.3.4**
  - nothing provides requested m2w64-flac 1.3.1**
  - nothing provides requested m2w64-gcc-libgfortran 5.3.0**
  - nothing provides requested m2w64-gcc-libs 5.3.0**
  - nothing provides requested m2w64-gcc-libs-core 5.3.0**
  - nothing provides requested m2w64-gettext 0.19.7**
  - nothing provides requested m2w64-gmp 6.1.0**
  - nothing provides requested m2w64-gsl 2.1**
  - nothing provides requested m2w64-libiconv 1.14**
  - nothing provides requested m2w64-libjpeg-turbo 1.4.2**
  - nothing provides requested m2w64-libogg 1.3.2**
  - nothing provides requested m2w64-libpng 1.6.21**
  - nothing provides requested m2w64-libsndfile 1.0.26**
  - nothing provides requested m2w64-libtiff 4.0.6**
  - nothing provides requested m2w64-libvorbis 1.3.5**
  - nothing provides requested m2w64-libwinpthread-git 5.0.0.4634.697f757**
  - nothing provides requested m2w64-libxml2 2.9.3**
  - nothing provides requested m2w64-mpfr 3.1.4**
  - nothing provides requested m2w64-pcre2 10.34**
  - nothing provides requested m2w64-speex 1.2rc2**
  - nothing provides requested m2w64-speexdsp 1.2rc3**
  - nothing provides requested m2w64-tcl 8.6.5**
  - nothing provides requested m2w64-tk 8.6.5**
  - nothing provides requested m2w64-tktable 2.10**
  - nothing provides requested m2w64-wineditline 2.101**
  - nothing provides requested m2w64-xz 5.2.2**
  - nothing provides requested m2w64-zlib 1.2.8**
  - nothing provides requested msys2-conda-epoch 20160418**
  - nothing provides requested pyreadline 2.1**
  - nothing provides requested vc 14.2**
  - nothing provides requested vs2015_runtime 14.27.29016**
  - nothing provides __win needed by wincertstore-0.2-pyhd8ed1ab_1009
  - package r-base-4.1.2-h2553ce4_1 requires icu >=69.1,<70.0a0, but none of the providers can be installed
  - package qt-main-5.15.3-hf97cb25_0 requires alsa-lib >=1.2.3,<1.2.4.0a0, but none of the providers can be installed
  - package python-3.7.4-h265db76_0 requires libffi >=3.2.1,<3.3a0, but none of the providers can be installed

The environment can't be solved, aborting the operation

```

Versions used

>conda 23.3.1
mamba (1.1.0)

**Comment by Rohit-Satyam** [comment]
hi @yuexujiang 

I tried the docker version and thank god it runs fine. However, I see a discrepancy in the results when compared to the website results and I think website uses the `fast` mode rather than `PSSM` mode, right?

`using fast mode`

```
>P10238:        Nucleus:0.49125221744179726     Cytoplasm:0.3964570499956608    Secreted:0.006795726716518402   Mitochondrion:0.002203088253736496      Membrane:0.0012977123260498047  Endoplasmic:0.0016651414334774017       Plastid:0.0027079954743385315   Golgi_apparatus:0.0031928718090057373   Lysosome:0.0043619535863399506  Peroxisome:0.0015493519604206085        prediction:Nucleus|
```

using `PSSM` mode

```
>P10238:        Nucleus:0.3198627941310406      Cytoplasm:0.6271803341805935    Secreted:0.00171685591340065    Mitochondrion:0.001420971006155014      Membrane:0.002649359405040741   Endoplasmic:0.0023099295794963837       Plastid:0.001708492636680603    Golgi_apparatus:0.002099510282278061    Lysosome:0.0025684721767902374  Peroxisome:0.0014800243079662323        prediction:Cytoplasm|
```

Besides, could you please revise the command in your README with this one coz that didn't work when using just `mulocdeep` rather than `mulocdeep/mulocdeep_stdalone`

```
sudo docker run -it -v ${workfolder}:${dockerfolder} mulocdeep/mulocdeep_stdalone python3 predict.py -input ${dockerfolder}/wiki.txt -output ${dockerfolder}/wiki_result_fast -mode fast
```

**Comment by yuexujiang** [comment]
Great, I was about to send you the version that runs on the server.
The website uses PSSM mode. I think the docker version is also hard-coded
as PSSM mode. How did you get the fast mode results?

**Comment by Rohit-Satyam** [comment]
>How did you get the fast mode results?


Accidently I ran `mulocdeep/mulocdeep_stdalone` instead of `mulocdeep/mulocdeep_stdalone:v2`. But I realised v2 is the latest. So yes, this issue is resolved for now but still if you can fix the conda version, I would be highly obliged. Running docker on workstation is fine but if I have to run MuLocDeep on HPC for faster results, conda will be helpful.

**Comment by yuexujiang** [comment]
Did you try the conda version downloaded from https://mu-loc.org/tools

**Comment by Rohit-Satyam** [comment]
@yuexujiang Yes I tried that one and that's the one that throws the `nothing provides requested m2w64-bwidget 1.9.10**` errors.

I have one more query @yuexujiang. Why don't people use the LOPIT experiment dataset as ground truth for training and testing their tools? These are experimental datasets cautiously labeled by experimentalists and scientists

**Comment by yuexujiang** [comment]
Sorry for the inconvenience. It is hard for me to fix the issue when I
cannot reproduce the error.

As to the benchmark dataset, I gave a glance at the paper you mentioned. I
think it is a very cool work. I guess that Nature protocol is more about
experiment and their dataset is not that ready for machine learning, and
they don't have a prediction performance to compare. While other papers,
for example, Deeploc, it organized the dataset very clearly, so people can
very quickly use it to train and test and compare.

**Comment by Rohit-Satyam** [comment]
#### Conda fix
Revisiting this thread just in case anyone else faces this issue in the future trying to install MulocDeep from [here](https://onedrive.live.com/?authkey=%21AIe9poBl8KGktlQ&id=158B8E4A4A833346%2143113&cid=158B8E4A4A833346).  This is what worked for me:

1. Removing the versions of the packages and the packages that were troubling such as `m2w64-bwidget` `vc` etc. Here is the revised yml content:

[revised.zip](https://github.com/yuexujiang/MULocDeep/files/14735568/revised.zip)



2. Post installation, activate the environment and then install the following package

```
pip install h5py==2.10.0
python3 predict.py -input test_seq/wiki_seq.txt  -output temp_res -species unknown
```
